### ISSUE TITLE
Question about production 

### ISSUE THREAD

**Issue by cactusgame** [ispamm/NAF-DPM#1]
Thank you for your work! I have some questions to ask.   
1. Does this model support the "shadow removing" task? 

2. For "Binarization" task, I find that the both DPM and  VIT model (like DocEnTr) takes a long time to do the prediction. (more than 20s under T4 GPU for a image's size  2000 * 2000 ) . For the ”Binarization“ task, what kind of model do you think is more suitable for use in a production environment?

**Comment by cactusgame** [comment]
Thanks for your reply!

The image with 2000*2000 resolution is indeed a large one, and I'm currently thinking about how to apply a similar model to products. However, a problem arises. Currently, most photos taken by smartphones are high-resolution, so I have to use a model to process images with big size. 

I've tried splitting the large image into several small patches (like 512*512), but it leads to a lack of global information in each patch, resulting in poor image processing results. I'm not sure if you have any suggestions?


> PS. 2000x2000 images are challenging for any generative model :)
I would try some algorithm that divides the image into smaller portions and in parallel processes those portions and then brings them together at the end of the pipeline.

**Comment by Giordano-Cicchetti** [comment]
You can try splitting the images into overlapping patches and then going to merge by averaging in the overlapping areas. I know this is not an optimal solution but it leads to a drastic reduction in inference time.

Regarding the structure of the model, I think the standard configuration of our deblurring model may work fine.

**Comment by cactusgame** [comment]
Thanks a lot! I'll have a try~
> You can try splitting the images into overlapping patches and then going to merge by averaging in the overlapping areas. I know this is not an optimal solution but it leads to a drastic reduction in inference time.
> 
> Regarding the structure of the model, I think the standard configuration of our deblurring model may work fine.
